Repository Paw565pl/compare-it, pull requests merged in 2024-12, with the labels that each got.

#2 FEAT(backend): create intial spring boot project
  .gitignore
  backend/.dockerignore
  backend/.editorconfig
  backend/.gitattributes
  backend/Dockerfile.dev
  backend/Dockerfile.prod
  backend/bruno/bruno.json
  backend/build.gradle.kts
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle.kts
  backend/src/main/java/it/compare/backend/Application.java
  backend/src/main/java/it/compare/backend/auth/config/SecurityConfig.java
  backend/src/main/java/it/compare/backend/core/config/ModelMapperConfig.java
  backend/src/main/java/it/compare/backend/core/exceptionhandler/ErrorResponse.java
  backend/src/main/java/it/compare/backend/core/exceptionhandler/GlobalExceptionHandler.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/it/compare/backend/ApplicationTests.java
  backend/src/test/java/it/compare/backend/TestBackendApplication.java
  backend/src/test/java/it/compare/backend/TestcontainersConfiguration.java
  docker-compose.dev.yml
Labels: enhancement

#6 FEAT(backend): rest client configuration
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/scraping/restclient/config/HttpRequestRetryStrategy.java
  backend/src/main/java/it/compare/backend/scraping/restclient/config/RestClientConfig.java
Labels: enhancement

#7 CI: create GitHub action for backend
  .github/workflows/javabuild.yml
  backend/build.gradle.kts
  backend/src/test/java/it/compare/backend/ApplicationTests.java
Labels: enhancement

#8 FEAT(backend): create product model
  backend/src/main/java/it/compare/backend/product/model/Category.java
  backend/src/main/java/it/compare/backend/product/model/Condition.java
  backend/src/main/java/it/compare/backend/product/model/Offer.java
  backend/src/main/java/it/compare/backend/product/model/PriceStamp.java
  backend/src/main/java/it/compare/backend/product/model/Product.java
  backend/src/main/java/it/compare/backend/product/model/Shop.java
  backend/src/main/java/it/compare/backend/product/repository/ProductRepository.java
Labels: enhancement

#10 FEAT(backend): create RTV Euro AGD scraper
  backend/src/main/java/it/compare/backend/Application.java
  backend/src/main/java/it/compare/backend/core/config/SecureRandomConfig.java
  backend/src/main/java/it/compare/backend/product/model/Offer.java
  backend/src/main/java/it/compare/backend/product/model/PriceStamp.java
  backend/src/main/java/it/compare/backend/product/model/Product.java
  backend/src/main/java/it/compare/backend/product/repository/ProductRepository.java
  backend/src/main/java/it/compare/backend/scraping/restclient/config/RestClientConfig.java
  backend/src/main/java/it/compare/backend/scraping/rtvauroagd/dto/RtvEuroAgdProduct.java
  backend/src/main/java/it/compare/backend/scraping/rtvauroagd/dto/RtvEuroAgdResponse.java
  backend/src/main/java/it/compare/backend/scraping/rtvauroagd/scraper/RtvEuroAgdScraper.java
  backend/src/main/java/it/compare/backend/scraping/rtvauroagd/scraper/RtvEuroAgdScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/rtvauroagd/watcher/RtvEuroAgdWatcher.java
  backend/src/main/java/it/compare/backend/scraping/service/ScrapingService.java
  backend/src/main/java/it/compare/backend/scraping/shopcategorymap/ShopCategoryMap.java
  backend/src/main/resources/application.yml
  backend/src/test/java/it/compare/backend/ApplicationTests.java
Labels: enhancement

#13 FEAT(backend): create product list and detail endpoints
  backend/src/main/java/it/compare/backend/product/controller/ProductRestController.java
  backend/src/main/java/it/compare/backend/product/mapper/ProductMapper.java
  backend/src/main/java/it/compare/backend/product/response/OfferResponse.java
  backend/src/main/java/it/compare/backend/product/response/PriceStampResponse.java
  backend/src/main/java/it/compare/backend/product/response/ProductDetailResponse.java
  backend/src/main/java/it/compare/backend/product/response/ProductListResponse.java
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
Labels: enhancement

#21 CHORE(backend): rename package with a typo
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/dto/RtvEuroAgdProduct.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/dto/RtvEuroAgdResponse.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/scraper/RtvEuroAgdScraper.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/scraper/RtvEuroAgdScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/watcher/RtvEuroAgdWatcher.java
Labels: invalid

#20 FIX(backend): correct name of shop in detail endpoint
  backend/src/main/java/it/compare/backend/product/response/OfferResponse.java
  backend/src/main/java/it/compare/backend/product/response/ProductListResponse.java
Labels: bug

#22 CI(frontend): create github action
  .github/workflows/frontendbuild.yml
Labels: enhancement
