Repository Paw565pl/compare-it, pull requests merged in 2025-04, with the labels that each got.

#96 TEST(backend): create integration tests for pricealert module
  backend/src/test/java/it/compare/backend/core/mock/AuthMock.java
  backend/src/test/java/it/compare/backend/pricealert/datafactory/PriceAlertTestDataFactory.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertControllerTest.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertRepositoryTest.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertTest.java
  backend/src/test/java/it/compare/backend/pricealert/unit/PriceAlertServiceTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductDetailsTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductListTest.java
  backend/src/test/java/it/compare/backend/user/datafactory/UserTestDataFactory.java
Labels: test

#95 TEST(backend): create integration tests for favoriteproduct module
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/favoriteproduct/service/FavoriteProductService.java
  backend/src/main/java/it/compare/backend/product/aggregation/ProductAggregationBuilder.java
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
  backend/src/test/java/it/compare/backend/core/datafactory/TestDataFactory.java
  backend/src/test/java/it/compare/backend/favoriteproduct/datafactory/FavoriteProductTestDataFactory.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductCreateTest.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductDeleteTest.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductListTest.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductStatusTest.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductTest.java
  backend/src/test/java/it/compare/backend/pricealert/datafactory/PriceAlertTestDataFactory.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertControllerTest.java
  backend/src/test/java/it/compare/backend/product/datafactory/ProductTestDataFactory.java
  backend/src/test/java/it/compare/backend/product/integration/ProductRepositoryTest.java
  backend/src/test/java/it/compare/backend/user/datafactory/UserTestDataFactory.java
Labels: test

#102 TEST(backend): create performance tests
  backend/.dockerignore
  backend/performance_tests/.gitignore
  backend/performance_tests/.python-version
  backend/performance_tests/pyproject.toml
  backend/performance_tests/requirements.txt
  backend/performance_tests/src/locustfile.py
  backend/performance_tests/uv.lock
Labels: test

#108 FIX(backend): permission issue in dockerfile prod
  backend/Dockerfile.dev
  backend/Dockerfile.prod
Labels: bug

#104 TEST(backend): create unit tests for scraping service
  backend/src/main/java/it/compare/backend/scraping/service/ScrapingService.java
  backend/src/test/java/it/compare/backend/scraping/unit/ScrapingServiceTest.java
Labels: test

#106 STYLE(frontend): adjust comment styles
  frontend/src/comments/components/comment-card/comment-card.tsx
  frontend/src/comments/components/comment-form/comment-form.tsx
  frontend/src/core/components/ui/alert-dialog.tsx
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/textarea.tsx
Labels: enhancement

#120 REFACTOR(backend): optimize products module queries
  backend/src/main/java/it/compare/backend/product/aggregation/ProductAggregationBuilder.java
  backend/src/main/java/it/compare/backend/product/model/Offer.java
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
  backend/src/test/java/it/compare/backend/comment/integration/CommentListTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductDetailsTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductListTest.java
Labels: refactor

#121 FEAT(frontend): update user object on token refresh
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/auth/auth.d.ts
  frontend/src/auth/config/auth-config.ts
  frontend/src/auth/types/token-refresh-response.ts
  frontend/src/auth/utils/create-tokens.ts
  frontend/src/auth/utils/create-user.ts
  frontend/src/auth/utils/refresh-tokens.ts
Labels: enhancement

#114 REFACTOR(frontend): adjust product components
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/h1.tsx
  frontend/src/favorite-products/hooks/query-options/get-favorite-product-status-query-options.ts
  frontend/src/products/components/product-actions-buttons/product-actions-buttons.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
Labels: refactor

#125 REFACTOR(backend): use database aggregation for price alerts logic
  backend/bruno/Price alerts/Delete all inactive alerts.bru
  backend/bruno/Price alerts/Get All.bru
  backend/src/main/java/it/compare/backend/pricealert/controller/PriceAlertController.java
  backend/src/main/java/it/compare/backend/pricealert/dto/PriceAlertFiltersDto.java
  backend/src/main/java/it/compare/backend/pricealert/model/PriceAlert.java
  backend/src/main/java/it/compare/backend/pricealert/response/PriceAlertResponse.java
  backend/src/main/java/it/compare/backend/pricealert/respository/PriceAlertRepository.java
  backend/src/main/java/it/compare/backend/pricealert/service/PriceAlertService.java
  backend/src/main/java/it/compare/backend/scraping/service/ScrapingService.java
  backend/src/test/java/it/compare/backend/pricealert/datafactory/PriceAlertTestDataFactory.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertControllerTest.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertIntegrationTest.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertRepositoryTest.java
  backend/src/test/java/it/compare/backend/pricealert/unit/PriceAlertServiceTest.java
  backend/src/test/java/it/compare/backend/product/datafactory/ProductTestDataFactory.java
  backend/src/test/java/it/compare/backend/scraping/unit/ScrapingServiceTest.java
Labels: refactor

#117 REFACTOR(frontend): use select for sort order and add availability filter
  .github/workflows/backend-build.yml
  .github/workflows/frontend-build.yml
  .github/workflows/javabuild.yml
  backend/src/main/java/it/compare/backend/Application.java
  backend/src/main/java/it/compare/backend/product/controller/ProductController.java
  frontend/package.json
  frontend/public/no-image-placeholder.svg
  frontend/src/app/globals.css
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/card.tsx
  frontend/src/core/components/ui/checkbox.tsx
  frontend/src/core/components/ui/dialog.tsx
  frontend/src/core/components/ui/h1.tsx
  frontend/src/core/components/ui/image-with-fallback.tsx
  frontend/src/core/components/ui/select.tsx
  frontend/src/core/components/ui/skeleton.tsx
  frontend/src/core/services/api/api-service.ts
  frontend/src/favorite-products/components/favorite-product-card/favorite-product-card.tsx
  frontend/src/favorite-products/components/favorite-products-grid/favorite-products-grid.tsx
  frontend/src/favorite-products/hooks/query-options/get-favorite-product-status-query-options.ts
  frontend/src/price-alerts/components/price-alert-card/price-alert-card.tsx
  frontend/src/price-alerts/components/price-alert-form-dialog/price-alert-form-dialog.tsx
  frontend/src/price-alerts/components/price-alert-notification-card/price-alert-notification-card.tsx
  frontend/src/price-alerts/components/price-alerts-grid/price-alerts-grid.tsx
  frontend/src/price-alerts/components/price-alerts-notifications-grid/price-alerts-notifications-grid.tsx
  frontend/src/products/components/categories-list/categories-list.tsx
  frontend/src/products/components/filters-bar/filters-bar.tsx
  frontend/src/products/components/index.ts
  frontend/src/products/components/product-list-page-header/product-list-page-header.tsx
  frontend/src/products/components/product-list/product-list.tsx
  frontend/src/products/components/product-page-images/product-page-images.tsx
  frontend/src/products/components/product-page-offers/product-page-offers.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/components/product-pagination/product-pagination.tsx
  frontend/src/products/components/single-offer/single-offer.tsx
  frontend/src/products/components/single-product/single-product.tsx
  frontend/src/products/components/sort-bar/sort-bar.tsx
  frontend/src/products/pages/product-list-page.tsx
  frontend/src/products/pages/product-page.tsx
  frontend/src/products/search-params/product-search-params.tsx
  frontend/src/profile/components/profile/profile.tsx
  frontend/src/profile/components/user-details-card/user-details-card.tsx
Labels: refactor

#126 FEAT(frontend): implement 404 and error page
  backend/src/main/java/it/compare/backend/comment/controller/CommentController.java
  backend/src/main/java/it/compare/backend/comment/service/CommentService.java
  backend/src/main/java/it/compare/backend/comment/validator/ValidCommentId.java
  backend/src/main/java/it/compare/backend/core/exceptionhandler/GlobalExceptionHandler.java
  backend/src/main/java/it/compare/backend/core/validator/ValidObjectId.java
  backend/src/main/java/it/compare/backend/favoriteproduct/controller/FavoriteProductController.java
  backend/src/main/java/it/compare/backend/favoriteproduct/dto/FavoriteProductDto.java
  backend/src/main/java/it/compare/backend/pricealert/controller/PriceAlertController.java
  backend/src/main/java/it/compare/backend/pricealert/dto/PriceAlertDto.java
  backend/src/main/java/it/compare/backend/pricealert/dto/PriceAlertFiltersDto.java
  backend/src/main/java/it/compare/backend/pricealert/validator/ValidPriceAlertId.java
  backend/src/main/java/it/compare/backend/product/controller/CategoryController.java
  backend/src/main/java/it/compare/backend/product/controller/ProductController.java
  backend/src/main/java/it/compare/backend/product/controller/ShopController.java
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
  backend/src/main/java/it/compare/backend/product/validator/ValidProductId.java
  backend/src/main/java/it/compare/backend/rating/controller/RatingController.java
  backend/src/main/java/it/compare/backend/rating/service/RatingService.java
  backend/src/test/java/it/compare/backend/favoriteproduct/integration/FavoriteProductCreateTest.java
  backend/src/test/java/it/compare/backend/pricealert/integration/PriceAlertControllerTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductDetailsTest.java
  frontend/src/app/error.tsx
  frontend/src/app/not-found.tsx
  frontend/src/core/libs/tanstack-query.ts
  frontend/src/core/pages/error-page.tsx
  frontend/src/core/pages/not-found-page.tsx
  frontend/src/core/utils/get-is-object-id-valid.ts
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/pages/product-page.tsx
Labels: enhancement

#123 REFACTOR(backend): refactor morele scraper
  backend/Dockerfile.dev
  backend/Dockerfile.prod
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/scraping/mediaexpert/scraper/MediaExpertScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/morele/scraper/MoreleScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/restclient/config/RestClientConfig.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/scraper/RtvEuroAgdScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/scheduler/ScrapingScheduler.java
  backend/src/main/java/it/compare/backend/scraping/scraper/ScrapingManager.java
  backend/src/main/java/it/compare/backend/scraping/util/ScrapingUtil.java
Labels: refactor

#130 FEAT(frontend): implement price history chart
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/src/app/globals.css
  frontend/src/comments/components/comment-card/comment-card.tsx
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/chart.tsx
  frontend/src/core/components/ui/dialog.tsx
  frontend/src/core/utils/format-date.ts
  frontend/src/products/components/index.ts
  frontend/src/products/components/price-history-chart-dialog/price-history-chart-dialog.tsx
  frontend/src/products/components/product-actions-buttons/product-actions-buttons.tsx
  frontend/src/products/components/product-page-offers/product-page-offers.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/components/sort-bar/sort-bar.tsx
  frontend/src/products/dtos/product-details-filters-dto.ts
  frontend/src/products/hooks/client/use-fetch-product.ts
  frontend/src/products/hooks/query-options/get-product-query-options.ts
  frontend/src/products/hooks/server/prefetch-product.ts
  frontend/src/products/pages/product-page.tsx
  frontend/src/products/utils/convert-price-data-to-chart-format.ts
Labels: enhancement

#132 FEAT(frontend): prepare for production
  backend/bruno/bruno.json
  backend/build.gradle.kts
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/src/main/resources/application-prod.yml
  docker-compose.dev.yml
  docker-compose.prod.yml
  frontend/.dockerignore
  frontend/.env.example
  frontend/.gitignore
  frontend/Dockerfile.prod
  frontend/components.json
  frontend/eslint.config.mjs
  frontend/next.config.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/android-chrome-192x192.png
  frontend/public/android-chrome-512x512.png
  frontend/src/app/api/auth/[...authjs]/route.ts
  frontend/src/app/apple-touch-icon.png
  frontend/src/app/favicon-16x16.png
  frontend/src/app/favicon-32x32.png
  frontend/src/app/favicon.ico
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/manifest.webmanifest
  frontend/src/app/page.tsx
  frontend/src/app/robots.txt
  frontend/src/auth/config/protected-routes.ts
  frontend/src/auth/utils/refresh-tokens.ts
  frontend/src/comments/components/comment-card/comment-card.tsx
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/navbar/sign-out-button.tsx
  frontend/src/core/components/ui/image-with-fallback.tsx
  frontend/src/core/layouts/root-layout.tsx
  frontend/src/core/libs/env/client-env.ts
  frontend/src/core/libs/env/server-env.ts
  frontend/src/core/pages/home-page.tsx
  frontend/src/core/providers/providers.tsx
  frontend/src/core/services/api/api-service.ts
  frontend/src/middleware.ts
  frontend/src/products/components/product-actions-buttons/product-actions-buttons.tsx
  frontend/src/products/components/single-product/single-product.tsx
  frontend/src/products/utils/get-shop-logo-url.ts
  frontend/tsconfig.json
Labels: enhancement
