Repository Paw565pl/compare-it, pull requests merged in 2025-03, with the labels that each got.

#71 FIX(CI): remove double calling github actions
  .github/workflows/frontendbuild.yml
  .github/workflows/javabuild.yml
Labels: enhancement

#69 FEAT(frontend): implement validation for comment form
  frontend/.dockerignore
  frontend/Dockerfile.prod
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/postcss.config.mjs
  frontend/src/app/globals.css
  frontend/src/comments/components/comment-card/comment-card.tsx
  frontend/src/comments/components/comment-form/comment-form.tsx
  frontend/src/comments/components/comments-section/comments-section.tsx
  frontend/src/comments/components/index.ts
  frontend/src/comments/schemas/comment-schema.ts
  frontend/src/core/components/navbar/logo.tsx
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/navbar/sign-in-button.tsx
  frontend/src/core/components/navbar/sign-out-button.tsx
  frontend/src/core/components/ui/alert-dialog.tsx
  frontend/src/core/components/ui/avatar.tsx
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/card.tsx
  frontend/src/core/components/ui/checkbox.tsx
  frontend/src/core/components/ui/dialog.tsx
  frontend/src/core/components/ui/form.tsx
  frontend/src/core/components/ui/input.tsx
  frontend/src/core/components/ui/label.tsx
  frontend/src/core/components/ui/select.tsx
  frontend/src/core/components/ui/textarea.tsx
  frontend/src/core/layouts/root-layout.tsx
  frontend/src/core/utils/format-currency.ts
  frontend/src/core/utils/format-date.ts
  frontend/src/favorite-products/components/favorite-product-card/favorite-product-card.tsx
  frontend/src/price-alerts/components/price-alert-card/price-alert-card.tsx
  frontend/src/price-alerts/components/price-alert-form-dialog/price-alert-form-dialog.tsx
  frontend/src/price-alerts/components/price-alert-notification-card/price-alert-notification-card.tsx
  frontend/src/products/components/categories-list/categories-list.tsx
  frontend/src/products/components/filter-bar/filter-bar.tsx
  frontend/src/products/components/index.ts
  frontend/src/products/components/product-actions-buttons/product-actions-buttons.tsx
  frontend/src/products/components/product-list/product-list.tsx
  frontend/src/products/components/product-page-comments/product-page-comments.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/components/single-offer/single-offer.tsx
  frontend/src/products/components/single-product/single-product.tsx
  frontend/src/products/components/sort-bar/sort-bar.tsx
  frontend/src/products/pages/product-list-page.tsx
  frontend/src/profile/components/profile/profile.tsx
  frontend/src/profile/components/user-details-card/user-details-card.tsx
  frontend/tailwind.config.ts
Labels: enhancement

#73 CHORE(backend): setup testcontainers
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/auth/config/SecurityConfig.java
  backend/src/main/java/it/compare/backend/pricealert/service/EmailService.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-test.yml
  backend/src/test/java/it/compare/backend/TestBackendApplication.java
  backend/src/test/java/it/compare/backend/TestcontainersConfiguration.java
  backend/src/test/java/it/compare/backend/core/config/FakerConfig.java
  backend/src/test/java/it/compare/backend/core/datafactory/TestDataFactory.java
  backend/src/test/java/it/compare/backend/core/mock/AuthMock.java
  backend/src/test/java/it/compare/backend/core/test/IntegrationTest.java
  backend/src/test/java/it/compare/backend/product/datafactory/ProductTestDataFactory.java
  backend/src/test/java/it/compare/backend/product/integration/ProductListTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductTest.java
  docker-compose.dev.yml
Labels: enhancement

#78 CHORE(backend): optimize dockerfiles
  backend/Dockerfile.dev
  backend/Dockerfile.prod
  docker-compose.dev.yml
  frontend/Dockerfile.prod
Labels: enhancement

#76 REFACTOR(frontend): remove api prefix from api base url
  frontend/.env.example
  frontend/src/comments/hooks/client/use-create-comment.ts
  frontend/src/comments/hooks/client/use-delete-comment.ts
  frontend/src/comments/hooks/client/use-update-comment.ts
  frontend/src/comments/hooks/query-options/get-comment-page-query-options.ts
  frontend/src/comments/hooks/query-options/get-comment-query-options.ts
  frontend/src/favorite-products/hooks/client/use-add-favorite-product.ts
  frontend/src/favorite-products/hooks/client/use-delete-favorite-product.ts
  frontend/src/favorite-products/hooks/query-options/get-favorite-products-page-query-options.ts
  frontend/src/price-alerts/hooks/client/use-create-price-alert.ts
  frontend/src/price-alerts/hooks/client/use-delete-price-alert.ts
  frontend/src/price-alerts/hooks/client/use-update-price-alert.ts
  frontend/src/price-alerts/hooks/query-options/get-price-alerts-page-query-options.ts
  frontend/src/products/hooks/query-options/categories-list-query-options.ts
  frontend/src/products/hooks/query-options/get-product-page-query-options.ts
  frontend/src/products/hooks/query-options/get-product-query-options.ts
  frontend/src/products/hooks/query-options/shops-list-query-options.ts
  frontend/src/rating/hooks/client/use-create-rating.ts
  frontend/src/rating/hooks/client/use-delete-rating.ts
  frontend/src/rating/hooks/client/use-update-rating.ts
  frontend/src/rating/hooks/query-options/get-rating-query-options.ts
Labels: enhancement

#82 FEAT(backend): create endpoint to check if product is favorite
  backend/bruno/Favorite Products/Add Favorite Product.bru
  backend/bruno/Favorite Products/Check If Product Is a Favorite.bru
  backend/bruno/Favorite Products/Delete Favorite Product.bru
  backend/src/main/java/it/compare/backend/favoriteproduct/controller/FavoriteProductController.java
  backend/src/main/java/it/compare/backend/favoriteproduct/repository/FavoriteProductRepository.java
  backend/src/main/java/it/compare/backend/favoriteproduct/response/FavoriteProductStatusResponse.java
  backend/src/main/java/it/compare/backend/favoriteproduct/service/FavoriteProductService.java
  frontend/src/favorite-products/entities/favorite-product-status-entity.ts
  frontend/src/favorite-products/hooks/client/use-add-favorite-product.ts
  frontend/src/favorite-products/hooks/client/use-favorite-product-status.ts
  frontend/src/favorite-products/hooks/query-options/get-favorite-product-status-query-options.ts
  frontend/src/favorite-products/hooks/server/prefetch-favorite-product-status.ts
Labels: enhancement

#80 FIX(frontend): reset filters and sort state on category change
  frontend/.env.example
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/ui/checkbox.tsx
  frontend/src/products/components/categories-list/categories-list.tsx
  frontend/src/products/components/filter-bar/filter-bar.tsx
  frontend/src/products/components/filters-bar/filters-bar.tsx
  frontend/src/products/components/index.ts
  frontend/src/products/pages/product-list-page.tsx
Labels: bug

#85 REFACTOR(frontend): Address issues related with design
  frontend/src/app/globals.css
  frontend/src/comments/components/comment-card/comment-card.tsx
  frontend/src/comments/components/comment-form/comment-form.tsx
  frontend/src/core/components/navbar/logo.tsx
  frontend/src/core/components/navbar/navbar.tsx
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/navbar/sign-in-button.tsx
  frontend/src/core/components/navbar/sign-out-button.tsx
  frontend/src/core/components/ui/button.tsx
  frontend/src/core/components/ui/checkbox.tsx
  frontend/src/core/components/ui/h2.tsx
  frontend/src/core/components/ui/h3.tsx
  frontend/src/core/components/ui/image-with-fallback.tsx
  frontend/src/core/components/ui/ul.tsx
  frontend/src/favorite-products/components/favorite-product-card/favorite-product-card.tsx
  frontend/src/price-alerts/components/price-alert-card/price-alert-card.tsx
  frontend/src/price-alerts/components/price-alert-form-dialog/price-alert-form-dialog.tsx
  frontend/src/price-alerts/components/price-alert-notification-card/price-alert-notification-card.tsx
  frontend/src/products/components/categories-list/categories-list.tsx
  frontend/src/products/components/filters-bar/filters-bar.tsx
  frontend/src/products/components/index.ts
  frontend/src/products/components/product-actions-buttons/product-actions-buttons.tsx
  frontend/src/products/components/product-list/product-list.tsx
  frontend/src/products/components/product-page-image/product-page-image.tsx
  frontend/src/products/components/product-page-images/product-page-images.tsx
  frontend/src/products/components/product-page-offers/product-page-offers.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/components/shop-image/shop-image.tsx
  frontend/src/products/components/single-offer/single-offer.tsx
  frontend/src/products/components/single-product/single-product.tsx
  frontend/src/products/components/sort-bar/sort-bar.tsx
  frontend/src/profile/components/profile/profile.tsx
  frontend/src/profile/components/user-details-card/user-details-card.tsx
Labels: enhancement

#84 REFACTOR(backend): use aggregation in database instead of java
  backend/bruno/Product/Product Details.bru
  backend/bruno/Product/Product List.bru
  backend/src/main/java/it/compare/backend/auth/model/User.java
  backend/src/main/java/it/compare/backend/comment/model/Comment.java
  backend/src/main/java/it/compare/backend/favoriteproduct/model/FavoriteProduct.java
  backend/src/main/java/it/compare/backend/pricealert/mapper/PriceAlertMapper.java
  backend/src/main/java/it/compare/backend/pricealert/model/PriceAlert.java
  backend/src/main/java/it/compare/backend/pricealert/service/PriceAlertService.java
  backend/src/main/java/it/compare/backend/product/aggregation/ProductAggregationBuilder.java
  backend/src/main/java/it/compare/backend/product/criteria/ProductSearchCriteria.java
  backend/src/main/java/it/compare/backend/product/dto/ProductFiltersDto.java
  backend/src/main/java/it/compare/backend/product/mapper/ProductMapper.java
  backend/src/main/java/it/compare/backend/product/model/Offer.java
  backend/src/main/java/it/compare/backend/product/model/PriceStamp.java
  backend/src/main/java/it/compare/backend/product/model/Product.java
  backend/src/main/java/it/compare/backend/product/response/OfferResponse.java
  backend/src/main/java/it/compare/backend/product/response/PriceStampResponse.java
  backend/src/main/java/it/compare/backend/product/response/ProductListResponse.java
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
  backend/src/main/java/it/compare/backend/rating/model/Rating.java
  backend/src/main/java/it/compare/backend/scraping/morele/scraper/MoreleScraperWorker.java
  backend/src/main/java/it/compare/backend/scraping/rtveuroagd/scraper/RtvEuroAgdScraperWorker.java
  backend/src/test/java/it/compare/backend/product/datafactory/ProductTestDataFactory.java
Labels: enhancement

#88 FIX(frontend): adjust entities types to match backend
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/comment/dto/CommentDto.java
  backend/src/main/java/it/compare/backend/product/aggregation/ProductAggregationBuilder.java
  backend/src/main/java/it/compare/backend/product/model/PriceStamp.java
  backend/src/main/java/it/compare/backend/product/response/PriceStampResponse.java
  backend/src/main/java/it/compare/backend/product/response/ProductListResponse.java
  frontend/.env.example
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/public/shop/morele_logo.webp
  frontend/public/shop/rtveuroagd_logo.webp
  frontend/src/comments/hooks/query-options/get-comment-page-query-options.ts
  frontend/src/core/components/navbar/navbar.tsx
  frontend/src/core/components/navbar/search-bar.tsx
  frontend/src/core/components/ui/input.tsx
  frontend/src/core/libs/env/client-env.ts
  frontend/src/core/providers/providers.tsx
  frontend/src/core/services/api/types/pagination-options.ts
  frontend/src/favorite-products/components/favorite-product-card/favorite-product-card.tsx
  frontend/src/favorite-products/hooks/query-options/get-favorite-products-page-query-options.ts
  frontend/src/price-alerts/hooks/query-options/get-price-alerts-page-query-options.ts
  frontend/src/products/components/categories-list/categories-list.tsx
  frontend/src/products/components/filters-bar/filters-bar.tsx
  frontend/src/products/components/index.ts
  frontend/src/products/components/product-list/product-list.tsx
  frontend/src/products/components/product-page-top/product-page-top.tsx
  frontend/src/products/components/product-pagination/product-pagination.tsx
  frontend/src/products/components/single-offer/single-offer.tsx
  frontend/src/products/components/single-product/single-product.tsx
  frontend/src/products/components/sort-bar/sort-bar.tsx
  frontend/src/products/entities/category-entity.ts
  frontend/src/products/entities/condition-entity.ts
  frontend/src/products/entities/offer-entity.ts
  frontend/src/products/entities/price-stamp-entity.ts
  frontend/src/products/entities/product-detail-entity.ts
  frontend/src/products/entities/product-list-entity.ts
  frontend/src/products/entities/shop-entity.ts
  frontend/src/products/hooks/client/use-fetch-product-page.ts
  frontend/src/products/hooks/query-options/get-product-page-query-options.ts
  frontend/src/products/hooks/server/prefetch-product-page.ts
  frontend/src/products/pages/product-list-page.tsx
  frontend/src/products/search-params/product-search-params.tsx
  frontend/src/products/utils/get-shop-logo-url.ts
Labels: bug

#89 TEST(backend): create integration tests for product module
  backend/build.gradle.kts
  backend/src/main/java/it/compare/backend/product/service/ProductService.java
  backend/src/test/java/it/compare/backend/core/test/IntegrationTest.java
  backend/src/test/java/it/compare/backend/product/datafactory/ProductTestDataFactory.java
  backend/src/test/java/it/compare/backend/product/integration/ProductDetailsTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductListTest.java
  backend/src/test/java/it/compare/backend/product/integration/ProductRepositoryTest.java
Labels: test
